// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbChGXLWW6yr817A7MI4vSQaVEHdhF1AI',
    appId: '1:331750600814:web:5b78c75f9c031f71aef67f',
    messagingSenderId: '331750600814',
    projectId: 'dropping-app-2025',
    authDomain: 'dropping-app-2025.firebaseapp.com',
    databaseURL: 'https://dropping-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'dropping-app-2025.firebasestorage.app',
    measurementId: 'G-3N9DJ1YFT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyZR-VFeMh4uc9aGMn1Bi0pjcw2jmbgo',
    appId: '1:331750600814:android:3335caf0124b3f50aef67f',
    messagingSenderId: '331750600814',
    projectId: 'dropping-app-2025',
    databaseURL: 'https://dropping-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'dropping-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4V0rgM_-p3O3_4Z82jtGWnf_lEYXkog',
    appId: '1:331750600814:ios:53220e6298d9afaeaef67f',
    messagingSenderId: '331750600814',
    projectId: 'dropping-app-2025',
    databaseURL: 'https://dropping-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'dropping-app-2025.firebasestorage.app',
    iosBundleId: 'com.droppingride.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI4V0rgM_-p3O3_4Z82jtGWnf_lEYXkog',
    appId: '1:331750600814:ios:4f25121a346d296caef67f',
    messagingSenderId: '331750600814',
    projectId: 'dropping-app-2025',
    databaseURL: 'https://dropping-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'dropping-app-2025.firebasestorage.app',
    iosBundleId: 'com.restart.tagxi.restartTagxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbChGXLWW6yr817A7MI4vSQaVEHdhF1AI',
    appId: '1:331750600814:web:270d25e1697924bcaef67f',
    messagingSenderId: '331750600814',
    projectId: 'dropping-app-2025',
    authDomain: 'dropping-app-2025.firebaseapp.com',
    databaseURL: 'https://dropping-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'dropping-app-2025.firebasestorage.app',
    measurementId: 'G-F3EQXMZ6C1',
  );
}
